alpaca_api_key: your_alpaca_api_key_here
alpaca_secret_key: your_alpaca_secret_key_here
base_url: https://paper-api.alpaca.markets
use_paper_trading: true
market_data_feed: iex
order_timeout: 60
max_order_retries: 3
max_positions: 10
max_daily_loss: 1000.0
position_size_percent: 0.02
stop_loss_percent: 0.02
take_profit_percent: 0.06
symbols_to_track:
- AAPL
- GOOGL
- MSFT
- AMZN
- TSLA
- META
- NVDA
- NFLX
- SPY
- QQQ
strategy_weights:
  moving_average_crossover: 0.3
  rsi_strategy: 0.3
  momentum_strategy: 0.2
  news_sentiment: 0.1
  price_forecast: 0.1
market_data_update_interval: 300
news_update_interval: 1800
strategy_evaluation_interval: 600
default_order_type: market
default_time_in_force: day
extended_hours: false
enable_websocket: true
websocket_reconnect_attempts: 5
websocket_reconnect_delay: 5
max_bars_per_request: 1000
rate_limit_requests_per_minute: 200
