repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.2
  hooks:
    # Run the linter in check mode - fails on any linting errors
    # - id: ruff-check
    #   args: [--fix, --exit-non-zero-on-fix]
    # Run the formatter.
    - id: ruff-format