# Consolidated AutoTrader Configuration
# =====================================
# Single configuration file for the entire trading system

# Application Configuration
app:
  name: "AutoTrader Pro"
  version: "1.0.0"
  environment: "production"  # development, staging, production
  debug: false

# Database Configuration
database:
  url: "sqlite:///data/trading.db"
  pool_size: 20
  max_overflow: 30
  echo: false

# Multi-Broker Configuration
# Each broker can be enabled/disabled independently
# Only one broker can be active at a time
brokers:
  # Alpaca Markets - Commission-free trading
  alpaca:
    enabled: true
    display_name: "Alpaca Markets"
    description: "Commission-free trading with excellent API"
    # Environment variables for credentials
    api_key: "${ALPACA_API_KEY}"
    api_secret: "${ALPACA_SECRET_KEY}" 
    # Trading configuration
    paper_trading: true
    base_url: "https://paper-api.alpaca.markets"
    market_data_feed: "iex"
    order_timeout: 60
    max_order_retries: 3
    extended_hours: false
    # WebSocket configuration
    enable_websocket: true
    websocket_reconnect_attempts: 5
    websocket_reconnect_delay: 5
    # Rate limiting
    rate_limit_requests_per_minute: 200
    max_bars_per_request: 1000
    
  # Interactive Brokers - Professional trading platform  
  interactive_brokers:
    enabled: false  # Set to true when ready to use
    display_name: "Interactive Brokers"
    description: "Professional trading platform with global markets"
    # Environment variables for credentials
    api_key: "${IB_API_KEY}"
    api_secret: "${IB_SECRET_KEY}"
    # Trading configuration
    paper_trading: true
    base_url: "https://api.interactivebrokers.com"
    order_timeout: 120
    max_order_retries: 3
    # TWS/Gateway settings
    tws_port: 7497  # 7497 for paper, 7496 for live
    client_id: 1
    
  # Demo Broker - For testing and development
  demo_broker:
    enabled: true
    display_name: "Demo Broker"
    description: "Simulated trading for testing (no real money)"
    # Demo credentials (not used for actual trading)
    api_key: "demo_key"
    api_secret: "demo_secret"
    # Configuration
    paper_trading: true
    base_url: "https://demo-api.example.com"
    starting_cash: 100000.0
    # Simulated market data
    mock_data: true
    price_simulation: true
    env_vars:
      api_key: "DEMO_API_KEY"
      secret_key: "DEMO_SECRET_KEY"
    base_url: "https://demo.api.com"
    paper_trading: true
    order_timeout: 30
    max_order_retries: 2

# Default broker selection
default_broker: "alpaca"  # Can be overridden by ACTIVE_BROKER environment variable
# Trading Configuration
trading:
  max_positions: 15
  max_daily_loss: 2000.0
  position_size_percent: 0.03  # 3% of portfolio per position
  stop_loss_percent: 0.03     # 3% stop loss
  take_profit_percent: 0.08   # 8% take profit
  order_timeout: 60
  max_order_retries: 3

# Strategy Configuration
strategies:
  enabled: true
  schedule: "*/10 * * * *"  # Every 10 minutes
  weights:
    moving_average_crossover: 0.25
    rsi_strategy: 0.25
    momentum_strategy: 0.20
    breakout_strategy: 0.15
    mean_reversion: 0.15
  signal_threshold: 0.6  # Minimum confidence score

# Automated Screening Configuration
screening:
  enabled: true
  schedule: "0 */1 * * *"  # Every hour
  max_symbols: 50
  criteria:
    min_price: 5.0
    max_price: 500.0
    min_volume: 250000
    min_daily_change: -15.0
    max_daily_change: 15.0
    exclude_penny_stocks: true

# Stock Scoring Configuration
scoring:
  enabled: true
  factors:
    momentum: 0.25
    volume: 0.20
    volatility: 0.15
    technical: 0.20
    sentiment: 0.10
    fundamentals: 0.10
  top_n_stocks: 30

# Risk Management Configuration
risk:
  enabled: true
  max_exposure_per_trade: 0.05     # 5% of portfolio
  max_exposure_per_sector: 0.20    # 20% of portfolio
  max_correlation: 0.7             # Maximum correlation between positions
  portfolio_risk_limit: 0.15      # 15% portfolio risk

# Monitoring Configuration
monitoring:
  enabled: true
  schedule: "*/5 * * * *"  # Every 5 minutes
  position_monitoring: true
  signal_monitoring: true

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  rotation: "daily"
  retention_days: 30

# Alert Configuration
alerts:
  enabled: true
  telegram:
    enabled: false
    # Credentials loaded from environment variables in code
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    # Credentials loaded from environment variables in code

# Data Update Intervals (in seconds)
data_updates:
  market_data: 300      # 5 minutes
  news_data: 1800       # 30 minutes
  fundamentals: 86400   # 24 hours

# Base Symbol Pool
base_symbols:
  - "AAPL"
  - "GOOGL"
  - "MSFT"
  - "AMZN"
  - "TSLA"
  - "META"
  - "NVDA"
  - "NFLX"
  - "SPY"
  - "QQQ"
  - "AMD"
  - "INTC"
  - "CRM"
  - "ADBE"
  - "PYPL"
