# Professional Automated Trading System Configuration
# =======================================================

# Application Configuration
app:
  name: "AutoTrader Pro"
  version: "1.0.0"
  environment: "production"  # development, staging, production
  debug: false
  
# Database Configuration
database:
  url: "sqlite:///data/trading.db"  # Use mounted volume in Docker
  pool_size: 20
  max_overflow: 30
  echo: false  # Set to true for SQL debugging
  
# Broker Configuration
broker:
  name: "alpaca"  # Currently only Alpaca supported
  paper_trading: true
  api_key: "${ALPACA_API_KEY}"
  secret_key: "${ALPACA_SECRET_KEY}"
  base_url: "https://paper-api.alpaca.markets"
  market_data_feed: "iex"
  
# Trading Configuration
trading:
  max_positions: 15
  max_daily_loss: 2000.0
  position_size_percent: 0.03  # 3% of portfolio per position
  stop_loss_percent: 0.03     # 3% stop loss
  take_profit_percent: 0.08   # 8% take profit
  order_timeout: 60
  max_order_retries: 3
  
# Automated Screening Configuration
screening:
  enabled: true
  schedule: "0 */1 * * *"  # Every hour (cron format)
  max_symbols: 50
  criteria:
    min_price: 5.0
    max_price: 500.0
    min_volume: 250000
    min_daily_change: -15.0
    max_daily_change: 15.0
    exclude_penny_stocks: true
    
# Stock Scoring Configuration
scoring:
  enabled: true
  factors:
    momentum: 0.25
    volume: 0.20
    volatility: 0.15
    technical: 0.20
    sentiment: 0.10
    fundamentals: 0.10
  top_n_stocks: 30  # Select top N stocks from screening
  
# Strategy Configuration
strategies:
  enabled: true
  schedule: "*/10 * * * *"  # Every 10 minutes
  weights:
    moving_average_crossover: 0.25
    rsi_strategy: 0.25
    momentum_strategy: 0.20
    breakout_strategy: 0.15
    mean_reversion: 0.15
  signal_threshold: 0.6  # Minimum confidence score
  
# Risk Management Configuration
risk:
  enabled: true
  max_exposure_per_trade: 0.05     # 5% of portfolio
  max_exposure_per_sector: 0.20    # 20% of portfolio
  max_correlation: 0.7             # Maximum correlation between positions
  portfolio_risk_limit: 0.15      # 15% portfolio risk
  
# Monitoring Configuration
monitoring:
  enabled: true
  schedule: "*/5 * * * *"  # Every 5 minutes
  position_monitoring: true
  signal_monitoring: true
  
# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  rotation: "daily"
  retention_days: 30
  
# Alert Configuration
alerts:
  enabled: true
  telegram:
    enabled: false
    bot_token: "${TELEGRAM_BOT_TOKEN}"
    chat_id: "${TELEGRAM_CHAT_ID}"
  email:
    enabled: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"
    
# Data Update Intervals (in seconds)
data_updates:
  market_data: 300      # 5 minutes
  news_data: 1800       # 30 minutes
  fundamentals: 86400   # 24 hours
  
# Base Symbol Pool (for initial screening)
base_symbols:
  - "AAPL"
  - "GOOGL"
  - "MSFT"
  - "AMZN"
  - "TSLA"
  - "META"
  - "NVDA"
  - "NFLX"
  - "SPY"
  - "QQQ"
  - "AMD"
  - "INTC"
  - "CRM"
  - "ADBE"
  - "PYPL"
