# Demo Broker Configuration
# This file contains broker-specific configuration settings for Demo Broker

broker_name: "demo_broker"
display_name: "Demo Broker"
broker_type: "demo"

# API Configuration
api:
  base_url: "https://demo-api.example.com"
  
# Trading Configuration
trading:
  supports_fractional_shares: true
  supports_crypto: false
  supports_options: false
  supports_futures: false
  
  # Order types supported
  order_types:
    - "market"
    - "limit"
    - "stop"
    - "stop_limit"
  
  # Time in force options
  time_in_force_options:
    - "day"
    - "gtc"  # Good Till Canceled

# Data Configuration
data:
  real_time_data: false
  historical_data: true
  news_data: false
  supports_level2: false
  
# Rate Limits (requests per minute)
rate_limits:
  orders: 100
  account_updates: 100
  market_data: 100
  
# Required Configuration Fields
# These will be validated when creating the broker adapter
required_config:
  - "api_key"
  - "secret_key"

# Default Configuration Values
defaults:
  paper_trading: true
  timeout: 30
  retry_attempts: 3
  retry_delay: 1
