# Demo Broker Configuration
demo_api_key: your_demo_api_key_here
demo_secret_key: your_demo_secret_key_here
base_url: https://demo-api.example.com
use_paper_trading: true
market_data_feed: demo
order_timeout: 30
max_order_retries: 2
max_positions: 5
max_daily_loss: 500.0
position_size_percent: 0.01
stop_loss_percent: 0.03
take_profit_percent: 0.05
symbols_to_track:
  - DEMO1
  - DEMO2
  - DEMO3
strategy_weights:
  moving_average_crossover: 0.4
  rsi_strategy: 0.3
  momentum_strategy: 0.3
market_data_update_interval: 60
news_update_interval: 3600
strategy_evaluation_interval: 300
default_order_type: limit
default_time_in_force: day
extended_hours: false
enable_websocket: false
rate_limit_requests_per_minute: 100
