# Base Trading System Configuration Template
# =========================================
# This file contains common settings that can be shared across all brokers

# Database Configuration
database_url: "sqlite:///trading.db"
database_pool_size: 10

# Logging Configuration
log_level: "INFO"
log_file: "trading.log"
log_rotation: "daily"
log_retention: 30  # days

# Common Risk Management Defaults
# (These can be overridden in broker-specific configs)
max_positions: 10
max_daily_loss: 1000.0
position_size_percent: 0.02  # 2% of portfolio per position
stop_loss_percent: 0.02      # 2% stop loss
take_profit_percent: 0.06    # 6% take profit

# Common Strategy Settings
strategy_weights:
  moving_average_crossover: 0.3
  rsi_strategy: 0.3
  momentum_strategy: 0.2
  news_sentiment: 0.1
  price_forecast: 0.1

# Common Update Intervals (seconds)
market_data_update_interval: 300   # 5 minutes
news_update_interval: 1800         # 30 minutes  
strategy_evaluation_interval: 600  # 10 minutes

# Common Trading Parameters
enable_live_trading: false
enable_backtesting: true
backtest_start_date: "2024-01-01"
backtest_end_date: "2024-12-31"

# Common Symbols (can be overridden by broker configs)
symbols_to_track:
  - "AAPL"
  - "GOOGL" 
  - "MSFT"
  - "AMZN"
  - "TSLA"
  - "META"
  - "NVDA"
  - "NFLX"
  - "SPY"
  - "QQQ"
