# inspired by https://jacobian.org/til/github-actions-poetry/

on:
    push:
      branches: [main]
    pull_request:
  
env:
    ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
    ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        max-parallel: 1
        fail-fast: false
        matrix:
          python-version: ["3.13"]
          os: [ubuntu-latest, macOS-latest]
      steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v6

        - name: Set up Python
          run: uv python install

        - name: Install the project
          run: uv sync --all-extras --dev

        - name: Run tests
          run: uv run pytest tests